# SwiftLint Configuration for Tennis Elbow App

# Paths to exclude from linting
excluded:
  - build
  - archives
  - fastlane
  - .build
  - DerivedData

# Opt-in rules (additional rules beyond defaults)
opt_in_rules:
  - empty_count
  - empty_string
  - explicit_init
  - fatal_error_message
  - first_where
  - closure_spacing
  - contains_over_first_not_nil
  - discouraged_optional_boolean
  - discouraged_optional_collection
  - force_unwrapping
  - implicit_return
  - multiline_arguments
  - multiline_function_chains
  - multiline_parameters
  - operator_usage_whitespace
  - overridden_super_call
  - prohibited_super_call
  - redundant_nil_coalescing
  - sorted_first_last
  - toggle_bool
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - yoda_condition

# Disabled rules
disabled_rules:
  - trailing_whitespace  # Can be handled by SwiftFormat
  - todo  # TODOs are acceptable in development

# Rule configurations
line_length:
  warning: 120
  error: 150
  ignores_comments: true
  ignores_urls: true

file_length:
  warning: 500
  error: 1000

function_body_length:
  warning: 50
  error: 100

type_body_length:
  warning: 300
  error: 500

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 50
    error: 60
  excluded:
    - id
    - x
    - y
    - i
    - j

cyclomatic_complexity:
  warning: 15
  error: 25

# Reporter type (xcode, json, csv, checkstyle)
reporter: "xcode"
