# ::: Code Generated by Copilot a0a3ad59-0c04-4219-b511-800b1eecb435. This comment will be removed automatically after the file is saved :::
PROJECT := TennisElbow/TennisElbow.xcodeproj
TARGET := TennisElbow
DERIVED := build
DEVICE ?= iPhone 16e
IPAD_DEVICE ?= iPad Pro 13-inch (M5)
BUNDLE_ID := com.madhouse.TennisElbow
APP := $(DERIVED)/Build/Products/Debug-iphonesimulator/TennisElbow.app

# ::: Code Generated by Copilot a0a3ad59-0c04-4219-b511-800b1eecb435. This comment will be removed automatically after the file is saved :::
SIM_UDID := $(shell xcrun simctl list devices available -j | python3 -c 'import json,re,sys; data=json.load(sys.stdin); devices=data.get("devices",{}); key=lambda rt: tuple(map(int,re.search("iOS-(\\d+)-(\\d+)",rt).groups())) if re.search("iOS-(\\d+)-(\\d+)",rt) else (-1,-1); runtimes=sorted(devices.keys(), key=key, reverse=True); udid=next((d.get("udid") for rt in runtimes for d in devices.get(rt,[]) if d.get("isAvailable") and d.get("name")==sys.argv[1]), None); print(udid or ""); sys.exit(0 if udid else 1)' "$(DEVICE)")

# ::: Code Generated by Copilot a0a3ad59-0c04-4219-b511-800b1eecb435. This comment will be removed automatically after the file is saved :::
IPAD_UDID := $(shell xcrun simctl list devices available -j | python3 -c 'import json,re,sys; data=json.load(sys.stdin); devices=data.get("devices",{}); key=lambda rt: tuple(map(int,re.search("iOS-(\\d+)-(\\d+)",rt).groups())) if re.search("iOS-(\\d+)-(\\d+)",rt) else (-1,-1); runtimes=sorted(devices.keys(), key=key, reverse=True); udid=next((d.get("udid") for rt in runtimes for d in devices.get(rt,[]) if d.get("isAvailable") and d.get("name")==sys.argv[1]), None); print(udid or ""); sys.exit(0 if udid else 1)' "$(IPAD_DEVICE)")

.PHONY: sim-boot sim-build sim-install sim-launch sim-run device-list clean archive open-xcode format
.PHONY: ipad-build ipad-install ipad-launch ipad-run screenshots screenshots-iphone screenshots-ipad process-screenshots
.PHONY: version bump-patch bump-minor bump-major bump-build

sim-boot:
	@test -n "$(SIM_UDID)" || (echo "Simulator device not found: $(DEVICE). Run 'make device-list' to see available devices." && exit 1)
	open -a Simulator || true
	xcrun simctl boot "$(SIM_UDID)" || true
	xcrun simctl bootstatus "$(SIM_UDID)" -b

sim-build:
	open -a Simulator || true

	xcodebuild \
	  -project "$(PROJECT)" \
	  -target "$(TARGET)" \
	  -configuration Debug \
	  -sdk iphonesimulator \
	  -destination "platform=iOS Simulator,name=$(DEVICE)" \
	  SYMROOT="$(CURDIR)/$(DERIVED)/Build/Products" \
	  OBJROOT="$(CURDIR)/$(DERIVED)/Build/Intermediates.noindex" \
	  clean build
	@echo "Build complete: $(APP)"

sim-install:
	@test -d "$(APP)" || (echo "App bundle not found at $(APP). Run 'make sim-build' first." && exit 1)
	@test -n "$(SIM_UDID)" || (echo "Simulator device not found: $(DEVICE). Run 'make device-list' to see available devices." && exit 1)
	xcrun simctl install "$(SIM_UDID)" "$(APP)"

sim-launch:
	@test -n "$(SIM_UDID)" || (echo "Simulator device not found: $(DEVICE). Run 'make device-list' to see available devices." && exit 1)
	xcrun simctl launch "$(SIM_UDID)" $(BUNDLE_ID)

sim-run: sim-boot sim-build sim-install sim-launch

ipad-build:
	open -a Simulator || true

	xcodebuild \
	  -project "$(PROJECT)" \
	  -target "$(TARGET)" \
	  -configuration Debug \
	  -sdk iphonesimulator \
	  -destination "platform=iOS Simulator,name=$(IPAD_DEVICE)" \
	  SYMROOT="$(CURDIR)/$(DERIVED)/Build/Products" \
	  OBJROOT="$(CURDIR)/$(DERIVED)/Build/Intermediates.noindex" \
	  clean build
	@echo "iPad build complete: $(APP)"

ipad-install:
	@test -d "$(APP)" || (echo "App bundle not found at $(APP). Run 'make ipad-build' first." && exit 1)
	@test -n "$(IPAD_UDID)" || (echo "Simulator device not found: $(IPAD_DEVICE). Run 'make device-list' to see available devices." && exit 1)
	xcrun simctl install "$(IPAD_UDID)" "$(APP)"

ipad-launch:
	@test -n "$(IPAD_UDID)" || (echo "Simulator device not found: $(IPAD_DEVICE). Run 'make device-list' to see available devices." && exit 1)
	xcrun simctl launch "$(IPAD_UDID)" $(BUNDLE_ID)

ipad-run: ipad-build ipad-install ipad-launch

screenshots:
	@echo "Capturing screenshots for all devices (iPhone and iPad)..."
	cd fastlane && bundle exec fastlane screenshots_all

screenshots-iphone:
	@echo "Capturing screenshots for iPhone devices only..."
	cd fastlane && bundle exec fastlane screenshots_iphone

screenshots-ipad:
	@echo "Capturing screenshots for iPad devices only..."
	cd fastlane && bundle exec fastlane screenshots_ipad

process-screenshots:
	@echo "Processing screenshots for App Store Connect..."
	cd fastlane && bundle exec fastlane process_screenshots

device-list:
	xcrun simctl list devices

clean:
	rm -rf "$(DERIVED)" archives

archive:
	mkdir -p archives

	xcodebuild \
	  -project "$(PROJECT)" \
	  -target "$(TARGET)" \
	  -configuration Release \
	  -destination "generic/platform=iOS" \
	  -archivePath "archives/TennisElbow.xcarchive" \
	  SYMROOT="$(CURDIR)/$(DERIVED)/Build/Products" \
	  OBJROOT="$(CURDIR)/$(DERIVED)/Build/Intermediates.noindex" \
	  -allowProvisioningUpdates \
	  clean archive
	@echo "Archive created at archives/TennisElbow.xcarchive"

open-xcode:
	open "$(PROJECT)"

format:
	@command -v swiftformat >/dev/null 2>&1 || { echo "Error: swiftformat not installed. Install with: brew install swiftformat"; exit 1; }
	cd TennisElbow && swiftformat .

# Version Management
version:
	@echo "Current version information:"
	@grep -m 1 "MARKETING_VERSION = " "$(PROJECT)/project.pbxproj" | sed 's/.*MARKETING_VERSION = \(.*\);/  Marketing Version: \1/'
	@grep -m 1 "CURRENT_PROJECT_VERSION = " "$(PROJECT)/project.pbxproj" | sed 's/.*CURRENT_PROJECT_VERSION = \(.*\);/  Build Number: \1/'

bump-patch:
	@bash scripts/version_bump.sh patch

bump-minor:
	@bash scripts/version_bump.sh minor

bump-major:
	@bash scripts/version_bump.sh major

bump-build:
	@bash scripts/version_bump.sh build

