# SwiftLint Configuration for Tennis Elbow App
# Aligned with SwiftFormat to prevent conflicts

# Paths to exclude from linting
excluded:
  - build
  - archives
  - fastlane
  - .build
  - DerivedData

# Opt-in rules (additional rules beyond defaults)
opt_in_rules:
  - empty_count
  - empty_string
  - explicit_init
  - fatal_error_message
  - first_where
  - closure_spacing
  - contains_over_first_not_nil
  - discouraged_optional_boolean
  - discouraged_optional_collection
  - force_unwrapping
  - multiline_arguments
  - multiline_function_chains
  - multiline_parameters
  - operator_usage_whitespace
  - overridden_super_call
  - prohibited_super_call
  - redundant_nil_coalescing
  - sorted_first_last
  - toggle_bool
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - yoda_condition

# Disabled rules - handled by SwiftFormat or conflict with it
disabled_rules:
  - trailing_whitespace           # Handled by SwiftFormat (trailingSpace)
  - todo                          # TODOs are acceptable in development
  - opening_brace                 # Handled by SwiftFormat (braces)
  - closure_end_indentation       # Handled by SwiftFormat (indent)
  - closure_parameter_position    # Handled by SwiftFormat (wrapArguments)
  - vertical_whitespace           # Handled by SwiftFormat (blankLines)
  - implicit_return               # SwiftFormat has its own implicit return handling
  - statement_position            # Handled by SwiftFormat (elseOnSameLine)
  - comma                         # Handled by SwiftFormat (spaceAroundComments)
  - colon                         # Handled by SwiftFormat (spaceAroundColons)
  - return_arrow_whitespace       # Handled by SwiftFormat (spaceAroundOperators)

# Rule configurations
line_length:
  warning: 120
  error: 150
  ignores_comments: true
  ignores_urls: true

file_length:
  warning: 500
  error: 1000

function_body_length:
  warning: 50
  error: 100

type_body_length:
  warning: 300
  error: 500

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 50
    error: 60
  excluded:
    - id
    - x
    - y
    - i
    - j

cyclomatic_complexity:
  warning: 15
  error: 25

# Reporter type (xcode, json, csv, checkstyle)
reporter: "xcode"
