# Snapfile for fastlane snapshot
# More info: https://docs.fastlane.tools/actions/snapshot/

# List of devices to generate screenshots for
# Using older device types to match App Store Connect requirements
devices([
  "iPad Pro 13-inch (M5)",    # 13" Display
  "iPhone 16 Pro Max",        # 6.9" Display
  "iPhone 11 Pro Max"         # 6.5" Display
])

# List of languages to generate screenshots for
languages([
  "en-US"
])

# The name of the scheme which contains the UI Tests
scheme("TennisElbow")

# Where should the resulting screenshots be stored?
output_directory("./fastlane/screenshots")

# Clear all previously generated screenshots before creating new ones
clear_previous_screenshots(true)

# Remove the '#' to clear all previously generated screenshots before creating new ones
override_status_bar(true)

# Arguments to pass to the app on launch
# launch_arguments(["-skipOnboarding"])

# For more information about all available options run
# fastlane action snapshot
