# Snapfile for fastlane snapshot
# More info: https://docs.fastlane.tools/actions/snapshot/

# List of devices to generate screenshots for
# Updated to use available simulators
devices([
  # iPhone devices
  "iPhone 17 Pro Max",
  "iPhone 17 Pro",
  "iPhone 17",
  "iPhone 16e",
  
  # iPad devices
  "iPad Pro 13-inch (M5)",
  "iPad Pro 11-inch (M5)",
  "iPad Air 13-inch (M3)",
  "iPad Air 11-inch (M3)"
])

# List of languages to generate screenshots for
languages([
  "en-US",
  "es-ES",
  "fr-FR",
  "de-DE",
  "ja-JP",
  "zh-Hans",
  "pt-PT",
  "it-IT",
  "nl-NL",
  "ko-KR"
])

# The name of the scheme which contains the UI Tests
scheme("TennisElbow")

# Where should the resulting screenshots be stored?
output_directory("../screenshots")

# Clear all previously generated screenshots before creating new ones
clear_previous_screenshots(true)

# Remove the '#' to clear all previously generated screenshots before creating new ones
override_status_bar(true)

# Arguments to pass to the app on launch
# launch_arguments(["-skipOnboarding"])

# For more information about all available options run
# fastlane action snapshot
